#!/usr/bin/env python3
"""Capa 医易: trigramas y 64 hexagramas → órganos, enfermedades y 食疗.

Vocabulario de escuela Yijing-médica y *Neijing*. Se nombra. No se dosifica.
"""

from __future__ import annotations

from tratado_salud import _u

# Zona por línea (abajo→arriba), tradición de cuerpo del hexagrama.
LINEA_ZONA = {
    1: "pies / primer yang, arranque",
    2: "pantorrillas y tendón, tierra baja",
    3: "muslos / ingle / paso al tronco",
    4: "tronco, diafragma, decisión",
    5: "pecho, cara, cargo del hexagrama",
    6: "cabeza, shen, lo que ya se pasa",
}

TRIGRAMA = {
    "乾": {
        "imagen": "Cielo",
        "elemento": "Metal",
        "zona": "cabeza, pulmón, intestino grueso, hueso, vértice",
        "zangfu": "pulmón / intestino grueso / cabeza-yang",
        "patrones": ["燥热伤津", "阳亢于巅", "金实不鸣"],
        "enfermedades": [
            "jaqueca de vértice",
            "calor de cabeza que no baja",
            "tos seca de metal",
            "estreñimiento de colon yang",
            "insomnio de creación que no apaga",
            "piel y pelo secos de cielo",
        ],
        "hierbas": ["麦冬", "玄参", "杏仁", "菊花", "石膏"],
        "alimentos": ["pera", "rábano blanco", "miel", "tofu"],
        "consejo": "El cielo no se empuja más: bajar la cabeza, humectar, callar el plan.",
    },
    "兑": {
        "imagen": "Lago",
        "elemento": "Metal",
        "zona": "boca, garganta, lengua, pulmón, habla",
        "zangfu": "pulmón / boca-metal",
        "patrones": ["肺开于口", "言多伤气", "燥咳少痰"],
        "enfermedades": [
            "afta y esquina de boca rota",
            "ronquera de hablar de más",
            "garganta que pica",
            "tos de lago (poca flema)",
            "diente o encía de metal",
            "risa que no cierra y deja vacío",
        ],
        "hierbas": ["桔梗", "甘草", "麦冬", "胖大海", "薄荷"],
        "alimentos": ["pera", "miel", "clara", "lirio"],
        "consejo": "El lago se cuida callando un rato y humectando la boca.",
    },
    "离": {
        "imagen": "Fuego",
        "elemento": "Fuego",
        "zona": "ojos, corazón, cara, vasos, lengua",
        "zangfu": "corazón / intestino delgado / ojo",
        "patrones": ["心火上炎", "目赤", "内热外干"],
        "enfermedades": [
            "ojo rojo o seco de fuego",
            "insomnio de brillo",
            "aftas y punta de lengua",
            "erupción de cara",
            "palpitación de adherencia",
            "sed que no se apaga",
        ],
        "hierbas": ["菊花", "决明子", "竹叶", "丹参", "莲子"],
        "alimentos": ["amargo corto", "loto", "sandía en mesura", "tomate"],
        "consejo": "El fuego se adhiere: sombra, menos pantalla, no alimentar el brillo.",
    },
    "震": {
        "imagen": "Trueno",
        "elemento": "Madera",
        "zona": "pies, hígado, vesícula, nervio, costado",
        "zangfu": "hígado / vesícula / tendón",
        "patrones": ["肝风内动", "惊则气乱", "筋脉拘急"],
        "enfermedades": [
            "sobresalto y tic",
            "calambre al arrancar",
            "jaqueca de sien de trueno",
            "tendón que salta",
            "vértigo de viento-madera",
            "insomnio de susto",
        ],
        "hierbas": ["钩藤", "天麻", "柴胡", "白芍", "龙骨"],
        "alimentos": ["ácido suave", "hoja verde", "apio", "sésamo negro"],
        "consejo": "El trueno pide tierra debajo: pies en el suelo, no más café de arranque.",
    },
    "巽": {
        "imagen": "Viento",
        "elemento": "Madera",
        "zona": "muslos, cadera, nervio, piel fina, decisión",
        "zangfu": "hígado / vesícula / viento",
        "patrones": ["风邪游走", "犹豫伤肝", "皮肤瘙痒"],
        "enfermedades": [
            "alergia que cambia de sitio",
            "picor de viento",
            "indecisión que contrae la cadera",
            "ciática de imagen de muslo",
            "ojo que lagrimea con viento",
            "ciclo o ánimo que no se afirma",
        ],
        "hierbas": ["防风", "薄荷", "白芍", "当归", "蝉蜕"],
        "alimentos": ["brote", "rosa cocina", "naba", "huevo"],
        "consejo": "El viento se domestica con dirección: un sí, un no, abrigo de nuca.",
    },
    "坎": {
        "imagen": "Agua",
        "elemento": "Agua",
        "zona": "oído, riñón, vejiga, sangre, lumbar",
        "zangfu": "riñón / vejiga",
        "patrones": ["肾虚水泛", "恐则气下", "寒水上逆"],
        "enfermedades": [
            "acúfeno y sordera de abismo",
            "lumbago frío",
            "edema",
            "orina frecuente de noche",
            "miedo que apaga el yang",
            "vértigo de agua",
        ],
        "hierbas": ["熟地", "茯苓", "桂枝", "杜仲", "泽泻"],
        "alimentos": ["poroto negro", "nuez", "caldo de hueso", "sésamo negro"],
        "consejo": "El abismo se cruza con calor de pies y reserva, no con más heroísmo.",
    },
    "艮": {
        "imagen": "Montaña",
        "elemento": "Tierra",
        "zona": "manos, espalda, nariz, articulación que frena",
        "zangfu": "bazo / estómago / hueso-freno",
        "patrones": ["气机停滞", "背脊强痛", "欲行不行"],
        "enfermedades": [
            "espalda que no dobla",
            "nuca y hombro de montaña",
            "mano rígida o tendón trabado",
            "estómago que se cierra y no baja",
            "insomnio de no poder parar ni seguir",
            "nariz tapada de tierra",
        ],
        "hierbas": ["白术", "厚朴", "葛根", "独活", "陈皮"],
        "alimentos": ["mijo", "calabaza", "cocido", "jengibre si hay frío"],
        "consejo": "La montaña se honra parando de verdad, no a medias.",
    },
    "坤": {
        "imagen": "Tierra",
        "elemento": "Tierra",
        "zona": "abdomen, bazo, estómago, carne, bajo vientre",
        "zangfu": "bazo / estómago",
        "patrones": ["脾虚湿困", "中气下陷", "腹满"],
        "enfermedades": [
            "hinchazón de centro",
            "heces sueltas",
            "edema blando",
            "cansancio de carne",
            "pensamiento que no cierra",
            "bajo vientre frío o pesado",
        ],
        "hierbas": ["茯苓", "白术", "山药", "甘草", "砂仁"],
        "alimentos": ["mijo", "ñame", "calabaza", "azufaifo"],
        "consejo": "La tierra pide horario y cocido, no más rumia en ayunas.",
    },
}

# Superposición propia de cada hexagrama (imagen + nombre), encima de los trigramas.
HEX = {
    1: {"eje": "yang que no baja de la cabeza",
        "enfermedades": ["insomnio de mando", "sequedad de cielo", "hipertensión de patrón yang (tratado)"],
        "consejo": "Crear menos rato. Humectar y recostar el vértice."},
    2: {"eje": "yin que recibe de más y se empapa",
        "enfermedades": ["edema de receptividad", "abdomen pesado", "flema de no elegir"],
        "consejo": "Recibir no es tragar todo. Secar con movimiento corto."},
    3: {"eje": "brote trabado en agua: no arranca",
        "enfermedades": ["pecho que no desciende", "digestión de comienzo", "ansiedad de primer paso"],
        "consejo": "Un solo paso pequeño. Calor en el centro, no más plan."},
    4: {"eje": "niebla sobre el agua: no ve",
        "enfermedades": ["flema que cubre el shen", "ojo nublado", "aprendizaje que empacha"],
        "consejo": "Menos dato, más caminata. El pupilo no se llena a la fuerza."},
    5: {"eje": "cielo sobre agua: esperar el vado",
        "enfermedades": ["sed y vejiga", "ansiedad de cola", "frío de pies con cabeza caliente"],
        "consejo": "Esperar comiendo caliente. No forzar el cruce."},
    6: {"eje": "agua contra cielo: pleito interno",
        "enfermedades": ["mandíbula y sien de conflicto", "gastritis de argumentar", "insomnio de razón"],
        "consejo": "Bajar el juicio. El hígado no es tribunal."},
    7: {"eje": "agua bajo tierra: campaña que gasta",
        "enfermedades": ["riñón de esfuerzo colectivo", "lumbar de cargar a otros", "sudor frío de tropa"],
        "consejo": "Retirar una batalla. La reserva no es cuartel."},
    8: {"eje": "tierra sobre agua: juntarse y empaparse",
        "enfermedades": ["humedad de vínculo", "hinchazón social", "flema de pertenecer"],
        "consejo": "Elegir un solo lazo. Secar el resto."},
    9: {"eje": "viento sobre cielo: acumular poco",
        "enfermedades": ["pulmón que no reparte", "alergia leve", "calor contenido en pecho"],
        "consejo": "Ventilar. No guardar el soplo."},
    10: {"eje": "cielo sobre lago: pisar con cuidado",
        "enfermedades": ["tendón de pie", "boca que se adelanta al cuerpo", "miedo de pisar mal"],
        "consejo": "Andar despacio. La palabra después del paso."},
    11: {"eje": "tierra sobre cielo: sube y baja bien",
        "enfermedades": ["si se rompe: reflujo o hundimiento", "cuando dura: centro estable"],
        "consejo": "No forzar la paz. Mantener el intercambio cielo-tierra: dormir y digerir."},
    12: {"eje": "cielo sobre tierra: no se hablan",
        "enfermedades": ["qi que no comunica", "pecho cerrado y abdomen frío", "estreñimiento de estancamiento"],
        "consejo": "Un hábito que baje y uno que suba: caminar después de comer."},
    13: {"eje": "cielo sobre fuego: calor de grupo",
        "enfermedades": ["fuego de corazón social", "ojo irritado de velada", "sudor de sala"],
        "consejo": "Salir del corrillo. Fuego con sombra."},
    14: {"eje": "fuego sobre cielo: posesión que quema",
        "enfermedades": ["estómago-fuego de abundancia", "encía y cara roja", "insomnio de tener"],
        "consejo": "Soltar un exceso. Amargo corto, no más banquete."},
    15: {"eje": "tierra sobre montaña: guardar el lomo",
        "enfermedades": ["espalda de modestia rígida", "estómago que se traga el orgullo", "nuca baja"],
        "consejo": "Inclinar de verdad, no aguantar encorvado."},
    16: {"eje": "trueno bajo tierra: entusiasmo que sacude el centro",
        "enfermedades": ["palpitación de fiesta", "estómago de euforia", "tendón que se adelanta"],
        "consejo": "El brote sale caminando, no gritando."},
    17: {"eje": "lago sobre trueno: seguir al brillo",
        "enfermedades": ["nervio que copia", "boca de decir que sí", "sueño arrastrado"],
        "consejo": "Seguir una sola cosa. Cerrar la boca un tramo."},
    18: {"eje": "montaña sobre viento: lo que se pudre si no se mira",
        "enfermedades": ["蛊 de tratado: humedad-calor crónica", "parásito de imagen", "estómago-hígado de asunto viejo"],
        "consejo": "Abrir la ventana. El viento preso se vuelve gu."},
    19: {"eje": "tierra sobre lago: lo que se acerca por abajo",
        "enfermedades": ["humedad de bajo vientre", "rodilla y tobillo", "flema que llega de a poco"],
        "consejo": "Recibir el acercamiento seco: movimiento, no más lago."},
    20: {"eje": "viento sobre tierra: mirar de lejos",
        "enfermedades": ["ojo de contemplar de más", "viento de nuca", "bazo que se olvida de comer"],
        "consejo": "Bajar la vista al plato. El paisaje no alimenta."},
    21: {"eje": "fuego sobre trueno: morder lo trabado",
        "enfermedades": ["diente, mandíbula, ATM", "estómago que no tritura", "ira de no pasar bocado"],
        "consejo": "Masticar de verdad. Un nudo por vez."},
    22: {"eje": "montaña sobre fuego: adorno que tapa",
        "enfermedades": ["piel y cara de gracia", "fuego contenido bajo el maquillaje", "estómago de parecer"],
        "consejo": "Menos brillo afuera, más sombra adentro."},
    23: {"eje": "montaña sobre tierra: se pela el yin",
        "enfermedades": ["diente flojo", "hueso que se descascara", "agotamiento de base"],
        "consejo": "Dejar que se caiga lo que ya no carga. Guardar jing."},
    24: {"eje": "tierra sobre trueno: el yang vuelve por abajo",
        "enfermedades": ["frío de pies que empieza a entrar", "lumbar de retorno", "depresión que cede un grado"],
        "consejo": "No acelerar el retorno. Calor abajo, no fuego arriba."},
    25: {"eje": "cielo sobre trueno: lo que llega sin aviso",
        "enfermedades": ["viento-golpe de tratado", "sobresalto de cielo", "tendón que se tuerce de pronto"],
        "consejo": "No interpretar el accidente como destino. Tierra y horario."},
    26: {"eje": "montaña sobre cielo: guardar demasiado",
        "enfermedades": ["nuca de acumular", "estómago de no soltar", "cabeza pesada de plan"],
        "consejo": "Vaciar un estante. La gran reserva también ahoga."},
    27: {"eje": "montaña sobre trueno: las fauces, nutrir",
        "enfermedades": ["boca, encía, maxilar", "nutrición irregular", "hambre de shen"],
        "consejo": "Comer a horario. La mandíbula no es el problema entero."},
    28: {"eje": "lago sobre viento: la viga se pasa de carga",
        "enfermedades": ["columna de preponderancia", "agotamiento de soporte", "pulmón-hígado de aguantar"],
        "consejo": "Bajar peso. La viga no se demuestra."},
    29: {"eje": "agua sobre agua: el pozo se repite",
        "enfermedades": ["riñón y miedo crónicos", "oído", "adicción de patrón agua"],
        "consejo": "Un solo borde del pozo. Calor y compañía seca."},
    30: {"eje": "fuego sobre fuego: se adhiere y quema",
        "enfermedades": ["ojo y corazón dobles", "erupción", "insomnio de mediodía"],
        "consejo": "Apagar una lámpara. El brillo no se apila."},
    31: {"eje": "lago sobre montaña: influjo, pareja, pericardio",
        "enfermedades": ["pecho de influjo", "ciclo o deseo irregular", "boca seca de emoción"],
        "consejo": "Sentir sin tragar entero. El lago no es contrato."},
    32: {"eje": "trueno sobre viento: duración que fatiga el tendón",
        "enfermedades": ["crónico de hígado", "hábito que no suelta", "tendón de insistir"],
        "consejo": "Duración no es terquedad. Un corte limpio."},
    33: {"eje": "cielo sobre montaña: retirarse a tiempo",
        "enfermedades": ["wei qi de retirada", "resfrío de no cubrirse", "espalda de huir a medias"],
        "consejo": "Retirada completa: abrigo, sueño, no media guerra."},
    34: {"eje": "trueno sobre cielo: poder que se pasa",
        "enfermedades": ["tendón de más", "hígado-yang", "jaqueca de fuerza"],
        "consejo": "El gran poder se guarda. Ácido suave, no más pelea."},
    35: {"eje": "fuego sobre tierra: subir a la vista",
        "enfermedades": ["ojo de progreso", "estómago-yangming", "cara que se enciende"],
        "consejo": "Subir con comida simple. El brillo no se desayuna en ayunas."},
    36: {"eje": "tierra sobre fuego: la luz herida",
        "enfermedades": ["depresión de fuego tapado", "ojo opaco", "pecho que no alumbra"],
        "consejo": "No forzar alegría. Guardar una lámpara chica."},
    37: {"eje": "viento sobre fuego: la casa, el clan",
        "enfermedades": ["bazo de familia", "preocupación de cocina", "pulmón de ambiente"],
        "consejo": "Un horario de casa. El clan no se digiere de noche."},
    38: {"eje": "fuego sobre lago: mirar en direcciones opuestas",
        "enfermedades": ["ojo de antagonismo", "boca contra corazón", "reflujo de no acordar"],
        "consejo": "No pelear con el plato. Un solo foco."},
    39: {"eje": "agua sobre montaña: cojera, el paso no da",
        "enfermedades": ["rodilla y pie de obstáculo", "miedo de avanzar", "riñón-montaña"],
        "consejo": "Otro camino, no más fuerza sobre la misma piedra."},
    40: {"eje": "trueno sobre agua: se suelta el nudo",
        "enfermedades": ["viento-humedad que se va", "espasmo que cede", "vejiga de alivio"],
        "consejo": "Soltar de verdad. Después, tierra para no recaer."},
    41: {"eje": "montaña sobre lago: mengua, se quita",
        "enfermedades": ["pérdida de yin/sangre de tratado", "boca seca de merma", "espalda de contener"],
        "consejo": "Menguar lo que sobra, no la reserva. Dormir."},
    42: {"eje": "viento sobre trueno: aumento que abre",
        "enfermedades": ["si se abusa: hígado que se pasa", "si se usa: recuperación de qi"],
        "consejo": "Aumentar comida y sueño, no estímulo."},
    43: {"eje": "lago sobre cielo: el yang rompe",
        "enfermedades": ["erupción de desborde", "calor que busca salida", "colon-pulmón de ruptura"],
        "consejo": "Dejar salir sin pelear. Frescura, no más filo."},
    44: {"eje": "cielo sobre viento: el encuentro súbito",
        "enfermedades": ["viento-calor de encuentro", "alergia nueva", "cabeza de imprevisto"],
        "consejo": "No tragarse el encuentro. Observar el poro."},
    45: {"eje": "lago sobre tierra: reunirse y condensar",
        "enfermedades": ["flema de reunión", "abdomen de banquete", "humedad de grupo"],
        "consejo": "Reunión corta. Después secar."},
    46: {"eje": "tierra sobre viento: subir desde el pozo",
        "enfermedades": ["qi hundido que pide alza", "prolapso de ritmo", "o hígado que sube de más"],
        "consejo": "Subir con horario, no con café. Tierra primero."},
    47: {"eje": "lago sobre agua: exhausto, boca seca y cuerpo húmedo",
        "enfermedades": ["sequedad de boca con edema", "ánimo de pozo", "pulmón-riñón de encierro"],
        "consejo": "Salir del recinto. Un sorbo tibio, no hielo."},
    48: {"eje": "agua sobre viento: el pozo, la fuente",
        "enfermedades": ["garganta y fuente de riñón", "fluido que no se saca", "cansancio de cántaro"],
        "consejo": "Cuidar la fuente: dormir, no agotar el pozo en charla."},
    49: {"eje": "lago sobre fuego: muda, piel, revolución",
        "enfermedades": ["piel que muda", "sarpullido de cambio", "pulmón-corazón de pelea"],
        "consejo": "Mudar por afuera con suavidad. Adentro, menos fuego."},
    50: {"eje": "fuego sobre viento: el caldero transforma",
        "enfermedades": ["estómago-caldero", "digestión de no transformar", "fuego de cocina interna"],
        "consejo": "Cocido y a horario. El ding no trabaja con crudo."},
    51: {"eje": "trueno sobre trueno: el susto se repite",
        "enfermedades": ["nervio y vesícula dobles", "sobresalto", "insomnio de trueno"],
        "consejo": "Tierra bajo los pies. Un solo ruido menos."},
    52: {"eje": "montaña sobre montaña: quietud que se vuelve traba",
        "enfermedades": ["espalda y mandíbula de frenar", "estómago detenido", "insomnio de no mover"],
        "consejo": "Parar el shen, mover las piernas. Quietud no es agarrotarse."},
    53: {"eje": "viento sobre montaña: el desarrollo lento",
        "enfermedades": ["articulación de avance gradual", "viento-humedad de rodilla", "cadera de espera"],
        "consejo": "Despacio y abrigado. El árbol no se tira."},
    54: {"eje": "trueno sobre lago: la muchacha que se casa, sangre",
        "enfermedades": ["ciclo de tratado", "hígado-sangre de vínculo", "pecho de entrega rápida"],
        "consejo": "No adelantar el vínculo. Nutrir sangre, no firmar con el tendón."},
    55: {"eje": "trueno sobre fuego: abundancia que enceguece",
        "enfermedades": ["golpe de calor", "ojo de mediodía", "corazón que se pasa de fiesta"],
        "consejo": "Recoger a media tarde. La abundancia se guarda."},
    56: {"eje": "fuego sobre montaña: el andariego, wei qi",
        "enfermedades": ["piel de viaje", "resfrío de posada", "estómago de horario roto"],
        "consejo": "Manta y comida conocida. El fuego viajero se apaga fácil."},
    57: {"eje": "viento sobre viento: lo suave que no decide",
        "enfermedades": ["alergia doble", "indecisión de cadera", "pulmón-hígado de no cortar"],
        "consejo": "Una dirección. El viento doble marea."},
    58: {"eje": "lago sobre lago: el gozo que se derrama",
        "enfermedades": ["boca y pulmón de más risa", "vacío después del brillo", "garganta de charla"],
        "consejo": "Gozo con borde. Callar es parte del lago."},
    59: {"eje": "viento sobre agua: se dispersa el shen",
        "enfermedades": ["sudor que dispersa", "ánimo que se esfuma", "viento sobre riñón"],
        "consejo": "Reunir: caldo, abrigo, una sola persona."},
    60: {"eje": "agua sobre lago: el límite, la articulación",
        "enfermedades": ["articulación seca o rígida", "vejiga de contención", "boca de decir no tarde"],
        "consejo": "El límite se pone antes. Agua tibia, no más hielo."},
    61: {"eje": "viento sobre lago: la verdad del centro",
        "enfermedades": ["bazo-corazón de fiarse", "flema de no decir", "pecho de sinceridad tragada"],
        "consejo": "Decir una cosa cierta. El centro se nutre simple."},
    62: {"eje": "trueno sobre montaña: lo pequeño se pasa",
        "enfermedades": ["temblor fino", "nervio de detalle", "tendón de exceso chico"],
        "consejo": "No cazar el pájaro con cañón. Menos estímulo."},
    63: {"eje": "agua sobre fuego: ya cruzó, se puede rigidizar",
        "enfermedades": ["corazón-riñón que ya conectaron y se traban", "ciclo cumplido que se seca", "estómago-fuego residual"],
        "consejo": "Después de completar, no apretar. Humectar y parar."},
    64: {"eje": "fuego sobre agua: aún no cruza, 心肾不交",
        "enfermedades": ["corazón y riñón que no se hablan", "insomnio de fuego arriba y frío abajo", "memoria de puente incompleto"],
        "consejo": "Bajar el fuego, calentar los pies. El cruce no se grita."},
}


def _tr(nombre: str) -> dict:
    return TRIGRAMA.get(nombre, {})


def paquete_hex(numero: int, inferior: str, superior: str,
                lineas_mutantes: list[int] | None = None) -> dict:
    low, up = _tr(inferior), _tr(superior)
    spec = HEX.get(int(numero), {})
    zonas = [LINEA_ZONA[i] for i in (lineas_mutantes or []) if i in LINEA_ZONA]
    enfermedades = _u(spec.get("enfermedades"), low.get("enfermedades"), up.get("enfermedades"))
    hierbas = _u(low.get("hierbas"), up.get("hierbas"))
    alimentos = _u(low.get("alimentos"), up.get("alimentos"))
    patrones = _u(low.get("patrones"), up.get("patrones"))
    consejos = _u(
        [spec.get("consejo")],
        [low.get("consejo")],
        [up.get("consejo")],
        [f"Línea mutante {i}: zona {LINEA_ZONA[i]}" for i in (lineas_mutantes or []) if i in LINEA_ZONA],
    )
    return {
        "numero": int(numero),
        "eje": spec.get("eje", ""),
        "inferior": inferior,
        "superior": superior,
        "zangfu_inferior": low.get("zangfu"),
        "zangfu_superior": up.get("zangfu"),
        "zona_inferior": low.get("zona"),
        "zona_superior": up.get("zona"),
        "zonas_mutantes": zonas,
        "patrones": patrones,
        "enfermedades": enfermedades,
        "hierbas": hierbas,
        "alimentos": alimentos,
        "consejos": [c for c in consejos if c],
        "nota": (
            "Capa 医易: trigrama inferior = constitución/zona baja; "
            "superior = lo que se manifiesta; núcleo = lo que no se ve. "
            "Se nombra. No se dosifica. No es verdad clínica."
        ),
    }
